### ISSUE TITLE
Compilation error after upgrading to 3.22.324.

### ISSUE THREAD

**Issue by muhuk** [Frege/eclipse-plugin#7]
After upgrading eclipse-plugin, I'm getting the same error on a number of my modules:

    flipƒ59a13447 cannot be resolved or is not a field

in file/FregeEuler/src/Euler02.fr, line 1. Here's the contents of the file:

```
module Euler02 where


fibs :: [Long]
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
 
 
euler02seq :: [Long]
euler02seq = [x | x <- takeWhile (<= 4000000) fibs, even x] 


main :: IO ()
main = do
    println "Euler02"
    println $ sum euler02seq
```

By commenting in/out, I've figure it's line 9, definition of euler02seq. It was working fine before I have upgraded. If there's a problem with my code, could you please point it out to me?

BTW the word `module` is underlined with red.

**Comment by muhuk** [comment]
Changing `(<= 4000000)` to `(\x -> x <= 4000000)` solved this particular problem for me. Aren't they equal expressions?

**Comment by Ingo60** [comment]
It should be the same. Well, not quite. To save a lambda, it is actually the same as

    Prelude.flip (<=) 400000

Copying your code into a fresh file works for me without problems.

To me it will seem that you upgraded from a 3.21. compiler version and didn't follow the advice given in the wiki, namely to do a clean rebuild.

So please, check the following:

  * in the Package Explorer, under "Referenced Libraries" you should see the fregec.jar and the actual path (in grey script). In the path, there should be a component starting with `frege.ide_3.22.nnn-` where 22.nnn is the Version you downloaded. If not, remove the fregec.jar from the build path and "Enable Frege Builder" anew on the project.

  * Turn off automatic building. Clean the project (Project -> Clean ...). Make sure there is nothing left below your bin/ (i.e.output) directory. Turn on automatic build again, if yoou like.

After that, it should re-compile everything and the error should be gone.

Btw, the output of your program is:

    Euler02
    4613732
    runtime 0.168 wallclock seconds.

**Comment by muhuk** [comment]
That solved it! Thanks.

I had a `plugins/frege.ide_3.22.92.201404261407/lib/fregec.jar`, now I'm using `plugins/frege.ide_3.22.335.201501171835/lib/fregec.jar`.

**Comment by Ingo60** [comment]
Yeah, this!

I shall find a way to make things less clumsy by updating the build path automatically.
